### ISSUE TITLE
OLAC2CMDI: accept `doi:` identifiers 

### ISSUE THREAD

**Issue by twagoo** [clarin-eric/metadata-conversion#5]
When processing `dc:identifier` while looking for resources, we now support 'regular' URLs, handles and urn:nbn. We could add DOI to that. A real use case of this popped up with the metadata provided by TROLLing ([OAI](https://dataverse.no/oai?verb=ListRecords&metadataPrefix=oai_dc&set=trolling)) where content like the following element can be found:
```xml
<dc:identifier>doi:10.18710/AGL9FD</dc:identifier>
```
Currently this is ignored. However, since DOI is a valid and common scheme, we could choose to accept it _as is_ (like we do with handle and urn:nbn), or be rewritten on the fly to a https://dx.doi.org/.... URL.

**Comment by dietervu** [comment]
We should support DOIs as mentioned above too.

**Comment by menzowindhouwer** [comment]
Implemented by #6
